name: 'Image Presence Audit Action'
description: 'A GitHub action that scans Kubernetes manifests in the repository to verify the existence of referenced container images.'
author: 'drumato'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  root:
    description: "The root directory from which the action will recursively search Kubernetes manifests."
    required: true
    default: '.'

# Define your outputs here.
outputs:
  count:
    description: "found manifest count"

runs:
  using: node20
  main: dist/index.js
